### ISSUE TITLE
[Sources] Icons missing for several providers

### ISSUE THREAD

**Issue by EasternPA** [fastenhealth/fasten-onprem#102]
Several provider icons are failing to load.

![360 care of alabama](https://user-images.githubusercontent.com/713544/225687362-964783d6-a69f-4320-a6bf-859548607f10.png)

**Comment by AnalogJ** [comment]
for anyone else that's watching following this issue, there's now a google spreadsheet where Fasten users can contribute logos and other metadata for their providers:

https://docs.google.com/spreadsheets/d/1ZSgwfd7kwxSnimk4yofIFcR8ZMUls0zi9SZpRiOJBx0/edit?usp=sharing

I'm going to close this as complete since this link is also present in the Fasten UI (when you click on a Source to connect it)

related #183
