### ISSUE TITLE
No Database file is generated at /opt/fasten/db/

### ISSUE THREAD

**Issue by vanimox** [fastenhealth/fasten-onprem#37]
This application looks very promising and I'm so glad something like this is finally being created. I just setup a docker instance, and this is what I found:

When using the following command, no database file is generated:

docker run --name=FastenHealth -p 9090:8080 -v /mnt/12Bay/docker/FastenHealth/db/:/opt/fasten/db/ ghcr.io/fastenhealth/fasten-onprem:main

**Comment by AnalogJ** [comment]
that's odd, it must be mis-configured somewhere. I recently did a full rewrite of Fasten's database layer, moving from CouchDB back to SQLite. 

I'm guessing I forgot a config file somewhere. I'll look into it.

**Comment by AnalogJ** [comment]
This was a simple fix - https://github.com/fastenhealth/fasten-onprem/commit/22f23e20f1e9df609f3d386ba48a73a4d6187371

But it took a while to release since I was having issues building the Docker image. 

It should be fixed now, so I'm going to close this issue. But feel free to comment/reopen if this is still a problem for you.
