### ISSUE TITLE
[Bug]: Labs Glossary Horizontal Overflow

### ISSUE THREAD

**Issue by mark-velez** [fastenhealth/fasten-onprem#408]
### What happened?

On the labs page, the glossary overflows horizontally over the dashboard card block for some content.

```
OS: Windows 11
Browser: Google Chrome 121.0.6167.140
```

![image](https://github.com/fastenhealth/fasten-onprem/assets/8049605/aef8983e-4d54-401c-8db1-0d0fd1bc5163)

![image](https://github.com/fastenhealth/fasten-onprem/assets/8049605/849ad72f-85a3-4068-8479-8c4b9da37fb5)

## Expected behavior
Glossary is contained within the dashboard card block.

## Possible fix
Removing `display: inline-block` rule from [glossary-lookup.component.scss#L4](https://github.com/fastenhealth/fasten-onprem/blob/main/frontend/src/app/components/glossary-lookup/glossary-lookup.component.scss#L4) using Developer Tools seems to fix-- I'm not sure if it breaks anything though.

### Flavor

Docker

### Version

main#74a1819

**Comment by AnalogJ** [comment]
hey @mark-velez 
My understanding is that this is due to the fact that the HTML provided by some [National Library of Medicine](https://www.nlm.nih.gov/) snippets is invalid (missing closing tags). 

While I haven't played with the `inline-block` class, I'm surprised that this would have an effect on this issue.
